### ISSUE TITLE
JWA: i18n Configuration Dropdowns

### ISSUE THREAD

**Issue by rohank07** [StatCan/jupyter-apis#104]
Add I18n for configurations dropdown which exist in poddefaults in personal ns
![image](https://user-images.githubusercontent.com/28408586/157305950-0058b0f8-a12e-43b9-8c1e-e0a0d2a2b338.png)

**Comment by brendangadd** [comment]
@rohank07 Can we reword the MinIO one at the same time?

> Mount MinIO storage to ~/minio (experimental) / \<fr-CA translation>
