### ISSUE TITLE
JWA: Fix Missing Tooltip

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#107]
The tooltip for start/stop is not working.

This is due to the action component. 

Some other PRs were fixed in similar fashion.

**Comment by mathis-marcotte** [comment]
This seems to be an issue from upstream 
![image](https://user-images.githubusercontent.com/84033116/196791421-6ecb0a8c-7bf4-411b-a55b-d20c393b0f35.png)
 
The tooltipInit and tooltipReady values get set, but never get retreived. Just the "tooltip" property gets called.
