### ISSUE TITLE
JWA: Missing i18n translations - OR translation not working

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#113]
There are many missing translations in jupyter-api
![image](https://user-images.githubusercontent.com/14837042/196687429-83aae5e6-8225-43be-9967-a923d6b8dbbf.png)

The 'name' is untranslated.
It comes from the volume.component.html
![image](https://user-images.githubusercontent.com/14837042/157692187-7e8a4d93-bc7a-4613-9c9f-698f0b787502.png)

**Comment by bryanpaget** [comment]
Related: https://github.com/StatCan/daaas/issues/1359

**Comment by wg102** [comment]
Yes, ticket is closed as 'already done'
