### ISSUE TITLE
Fix: Enable Kubecost Table

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#123]
The table was hardcoded as unavailable following this : https://github.com/StatCan/jupyter-apis/issues/110
It will need investigation to see why the table does not display the information properly

- [ ] Read the original issue and the code request
- [ ] Put the code back 
- [ ] See if there are any errors 
- [ ] Investigate why the original issue happened
- [ ] Possibly fake data to insure it get there

**Comment by Jose-Matsuda** [comment]
![image](https://user-images.githubusercontent.com/23174198/185431948-234b0044-2e1b-407a-bd05-97f503585804.png)
Yup everything seems to work just fine
