### ISSUE TITLE
Upgrade 1.6: Fix Backend

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#125]
See issue https://github.com/StatCan/daaas/issues/1242
This issue is part of the whole upgrade kubeflow.

The items or specifics will be written down after talking to Will.
After a quick chat with Will, it seems the way they have done the update previously is to launch the upstream jupyter-api, then open devtools and take a look at any of the requests that the webapp is making to the backend, along with their payloads and then update the golang schema for any corrections.

There are 3 parts of this issue: It might be wise to split the ticket in 3 as well?
Jupyter
Tensorboards
Volumes

This being said, we don't have the same UI as they do.
Per example, our Jupyter has some option theirs don't.
We use our own volume table. Might have changed. 
We do not yet use Tensorboards, but we might want to include it. 

# TODO

- [ ] Compare 1.6 crud web apps python application to the jupyter-web-apis golang application and review the logic endpoint by endpoint (make sure source code does the same thing in each case).
- [ ] Test every case live against the aaw-dev cluster (e.g. once jupyter-web-apis is refactored, run it locally connecting to aaw-dev cluster and e.g. make postman requests for each endpoint case - include postman tests in jupyter-apis repo).

**Comment by Collinbrown95** [comment]
# Notes from meeting

- this relates to the notebook tab in the central dashboard menu
- the "new server" part is also part of jupyter apis

## Development Workflow

**Note**: 2 ways to set this up (1) connect to dev cluster directly or (2) mock k3d cluster and point jupyter-web api to k3d cluster

1. Run upstream version of app https://github.com/kubeflow/kubeflow/tree/v1.4.0/components/crud-web-apps 
    - need to run each of these **(jupyter and volumes)** independently locally as their own web app, instructions are in README of each folder.

2. Run our home grown version of jupyter webapps



## Features to test

**jupyter APIs**

- RESTART CREATE DELETE STOP notebooks

**volume table**

- we have our own home-grown version of this that is completely separate from the upstream code.
