### ISSUE TITLE
fix-1.6 Add Environment Variable

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#134]
This ticket is part of the Work to re apply to jupyter-apis. 

The original work was done in the following tickets:
| Original Title                                  | Date     | Description                  | PR # | Note                     |
| ----------------------------------------------- | -------- | ---------------------------- | ---- | ------------------------ |
| Merge pull request 48 from StatCan/feat-env-var | 21/01/21 | StatCan/jupyter-apis@2c1532b | 48   | Add env var for notebook |

This feature add a section to the 'Advanced features' when creating a new notebook. And depending on the value selected, that value is passed to the image as an environment variable. 
Allowing someone to create a new notebook, that by default, will be in their prefered language.

**Comment by mathis-marcotte** [comment]
A commit in the table (PR #48 ) includes changes done in the back end. So this issue will be put on hold while while the backend gets updated to version 1.6.

**Comment by mathis-marcotte** [comment]
Checked up with the backend and things are done now
