### ISSUE TITLE
fix-1.6 Add Hint text

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#136]
This ticket is part of the work to re-apply for the 1.6 upgrade for jupyter apis.
The original work was done in these tickets:
| Original Title                                                    | Date     | Description                  | PR # | Note                                                                   |
| ----------------------------------------------------------------- | -------- | ---------------------------- | ---- | ---------------------------------------------------------------------- |
| Merge pull request #60 from StatCan/image-selection-hint          | 21/04/20 | StatCan/jupyter-apis@5daefc3 | 60   | Add image text hint                                                    |            
| Merge pull request #30 from StatCan/Change-the-hint-image-message | 20/10/14 | StatCan/jupyter-apis@9d02488 | 30   | Change a message	SHouldnt need should be with i18n X (merge with i18n) |    

This seems to just be updates to the text in the form used to create notebooks.

**Comment by Jose-Matsuda** [comment]
idk why this didnt close
