### ISSUE TITLE
fix-1.6 Modify limits, gpus and cpus

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#137]
This ticket is part of the work to re-apply for the 1.6 upgrade for jupyter apis.
The original work was done in these tickets:
| Original Title                                            | Date     | Description                  | PR # | Note                                            |
| --------------------------------------------------------- | -------- | ---------------------------- | ---- | ----------------------------------------------- |
| Merge pull request #38 from StatCan/fix-max-limits        | 20/11/03 | StatCan/jupyter-apis@344d4fc | 38   | fix: update ram limitsX - find where merge with |            
| Merge pull request #45 from StatCan/fix-gpu-specs         | 20/12/16 | StatCan/jupyter-apis@0e116fd | 45   | Validation GPU                                  |            
| Merge pull request #57 from StatCan/lower-gpu-cpu-request | 21/02/16 | StatCan/jupyter-apis@0b55d4d | 57   | lower-gpu-cpu-request                           |            
| feat: change cpu limit                                    | 22/04/11 | StatCan/jupyter-apis@bdf857c | 119  | change cpu limit                                |            

This seems to relate to adding limits to the CPU/GPU fields in the form for creating a notebook

**Comment by mathis-marcotte** [comment]
Waiting on #138 since this seems to be related
