### ISSUE TITLE
fix-1.6 Validation

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#138]
This ticket is part of the work to re-apply for the 1.6 upgrade for jupyter apis.
The original work was done in these tickets:

| Original Title                                                         | Date     | Description                  | PR # | Note                                                                 |
| ---------------------------------------------------------------------- | -------- | ---------------------------- | ---- | -------------------------------------------------------------------- |
| Merge pull request #19 from StatCan/notebook-server-validation         | 20/09/16 | StatCan/jupyter-apis@22bdc13 | 19   | Name validation, CPu error, component error, default values	X - VERY |            
| Merge pull request #51 from StatCan/50-add-validation-mounted-pvc      | 21/01/07 | StatCan/jupyter-apis@8641aab | 51   | Validation Mounted volume	X                                          |            
| Merge pull request #61 from StatCan/59-add-custom-image-url-validation | 21/05/21 | StatCan/jupyter-apis@416bcb1 | 61   | custom-image-url-validation	X                                        |            

This seems to relate to adding some validation to the form used for creating notebooks

## Important Notes
[volume](https://github.com/kubeflow/kubeflow/tree/v1.4-branch/components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume) was reworked and looks different in [1.6](https://github.com/kubeflow/kubeflow/tree/v1.6-branch/components/crud-web-apps/jupyter/frontend/src/app/pages/form/form-default/volume), so I removed these.
![image](https://user-images.githubusercontent.com/23174198/192325417-b1fe2c5f-7a50-4d1a-a925-491911b4f37d.png)

## Reminders for JOSE

Going to give myself all powerful permissions across DEV for pvcs, this will be attached to my own account and will have the jose-pvc prefix on all resources

**Comment by Jose-Matsuda** [comment]
Work is being done in this [branch](https://github.com/StatCan/jupyter-apis/tree/1.6-fix-validation) which was created off of Mathis' [upgrade-frontend-1.6](https://github.com/StatCan/jupyter-apis/tree/upgrade-frontend-1.6) in his [pr](https://github.com/StatCan/jupyter-apis/pull/132). We will eventually merge my `1.6-fix-validation` branch into that `upgrade-frontend-1.6` branch

**Comment by Jose-Matsuda** [comment]
## https://github.com/StatCan/jupyter-apis/pull/19 Notes:

In looking at upstream where they made [modifications to the way volumes were managed](https://github.com/kubeflow/kubeflow/pull/6321) it seems they allowed for freedom in letting users choose their size. 
Having said that, if nothing on our side has changed, we want to keep it at the [4 - 512 Gi option](https://github.com/StatCan/jupyter-apis/issues/7#issuecomment-687249223)

**Comment by Jose-Matsuda** [comment]
## https://github.com/StatCan/jupyter-apis/pull/51 Notes: Refer to https://github.com/StatCan/jupyter-apis/issues/50 for more info

**Comment by Jose-Matsuda** [comment]
## https://github.com/StatCan/jupyter-apis/pull/61 Notes: Refer to https://github.com/StatCan/jupyter-apis/issues/59 for more info.

Yeah seems like they really dont have any validation unfortunately

**Comment by Jose-Matsuda** [comment]
### Confusions on my end.

Am looking at https://github.com/StatCan/jupyter-apis/blob/1290ff2854215091231c988bf59cd712fcdd24fa/frontend/jupyter/src/app/pages/form/form-default/form-workspace-volume/form-workspace-volume.component.html#L76 and here i see it uses `<app-new-volume` compared to what was used before in https://github.com/StatCan/jupyter-apis/blob/1ca7a351e92efd22080282774b8cfa4dcaef14b4/frontend/jupyter/src/app/pages/form/form-default/form-workspace-volume/form-workspace-volume.component.html#L11

Now does this mean that I need to modify whatever the `selector` for `app-new-volume` is? as in this new file https://github.com/StatCan/jupyter-apis/blob/1290ff2854215091231c988bf59cd712fcdd24fa/frontend/jupyter/src/app/pages/form/form-default/volume/new/new.component.ts#L15

**Comment by Jose-Matsuda** [comment]
Ok i thought there was duplicated code [here](https://github.com/StatCan/jupyter-apis/blob/1ca7a351e92efd22080282774b8cfa4dcaef14b4/frontend/jupyter/src/app/pages/form/form-default/form-cpu-ram/form-cpu-ram.component.ts#L55) but it really seems like it is necessary.


![image](https://user-images.githubusercontent.com/23174198/192605148-5f1a10de-3d0e-4c4b-be28-6f8bdba66df8.png)

**Comment by Jose-Matsuda** [comment]
WHY DIDNT THIS CLOSE
