### ISSUE TITLE
fix-1.6 Add Volume Table

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#139]
This ticket is part of the work to re-apply for the 1.6 upgrade for jupyter apis.
The original work was done in these tickets:

| Original Title                                                    | Date     | Description                  | PR # | Note           |
| ----------------------------------------------------------------- | -------- | ---------------------------- | ---- | -------------- |
| Merge pull request #20 from StatCan/18-destroy-old-notebooks      | 20/10/06 | StatCan/jupyter-apis@2e9daf6 | 20   | VOLUME TABLE   |            
| Merge pull request #29 from StatCan/28-data-volume-ui-is-squashed | 20/10/07 | StatCan/jupyter-apis@738e6fd | 29   | fix CSS VoLUME |        

This relates to adding back the Volume table

**Comment by Jose-Matsuda** [comment]
idk why this didnt close
