### ISSUE TITLE
fix-1.6 add Kubecost

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#140]
This ticket is part of the work to re-apply for the 1.6 upgrade for jupyter apis.
The original work was done in these tickets:

| Original Title                                           | Date     | Description                  | PR #        | Note                   |
| -------------------------------------------------------- | -------- | ---------------------------- | ----------- | ---------------------- |
| Merge pull request #27 from StatCan/kubecost-estimates   | 20/10/21 | StatCan/jupyter-apis@49dea69 | 27	Kubecost |                        |            
| Merge pull request #34 from StatCan/fix-kubecost-error   | 20/11/06 | StatCan/jupyter-apis@d412a39 | 34	fix      | kubecost               |            
| Merge pull request #40 from StatCan/fix-kubecost-message | 20/11/10 | StatCan/jupyter-apis@0fba437 | 40          | fix kubecost message - |        
| feat: bring back cubecost table | 22/08/118 | StatCan/jupyter-apis@9835ca1 | 124 |       

This relates to adding back the Kubecost table.

**Comment by Jose-Matsuda** [comment]
idk why this didnt close
