### ISSUE TITLE
fix-1.6 Add Pro B volumes

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#141]
This ticket is part of the work to re-apply for the 1.6 upgrade for jupyter apis.
The original work was done in these tickets:
| Original Title            | Date     | Description                  | PR # | Note              |
| ------------------------- | -------- | ---------------------------- | ---- | ----------------- |
| fix(prob volumes)         | 21/09/22 | StatCan/jupyter-apis@da808ea | 63   | prob Volume       |            
| fix(use the better label) | 21/09/22 | StatCan/jupyter-apis@e0a6302 | 64   | add-prob-volv2    |            
| add prob volume label     | 21/09/29 | StatCan/jupyter-apis@24e2ce1 | 66   | prob-volume-label |    

This seems to relate to adding pro B volumes to the notebook creation process

**Comment by Jose-Matsuda** [comment]
The commits here are all related to the _backend_ meaning this is likely Christian (not the Religion) work. 
So this is already done / out of my hands I think.

I did however spend just a bit of time confirming things just in case someone winds up here;

1) These changes are in `notebooks.go`, something that again Christian is working on and looking at his commit [here](https://github.com/StatCan/jupyter-apis/blob/2e2dc581bcee137cf403e16abf41af7fdc10974a/README.md) where he links the `POST` for `notebook` creation, I think we are fine. Could come up in his issue regarding [auditing endpoints](https://github.com/StatCan/daaas/issues/1355) so we will see. 

2) Recall that the dropdown is populated by `PodDefaults` which we can find in the [`aaw-kubeflow-profiles-controller`](https://github.com/StatCan/aaw-kubeflow-profiles-controller/blob/bf4c3b330be04e3dc484f6debd6422e2320f642b/cmd/notebook.go#L164)
