### ISSUE TITLE
fix-1.6 Image pull policy + Fix

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#142]
This ticket is part of the Work to re apply to jupyter-apis.

The original work was done in the following tickets:
| Original Title                          | Date     | Description                  | PR # | Note                     |
| --------------------------------------- | -------- | ---------------------------- | ---- | ------------------------ |
| feat(imagePullPolicy): Change to Always | 22/05/04 | StatCan/jupyter-apis@2113334 | 120  | image pull policy change |            
| feat(imagePullPolicy): Add and set it   | 22/06/06 | StatCan/jupyter-apis@d105c5a | 121  | One weird change?        |       

I think the work was litterally to change the pull policy, then undo some code that was pushed by mistake.

**Comment by mathis-marcotte** [comment]
A commit in the table (PR #121) includes changes done in the back end. So this issue will be put on hold while while the backend gets updated to version 1.6.

**Comment by mathis-marcotte** [comment]
Checked up with the backend and things are done now
