### ISSUE TITLE
1.6: Fix volumes

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/jupyter-apis#158]
This can be a few things

1)We brought in our changes, but there is a failure upon trying to create a notebook server

The `POST` is failing 

![image](https://user-images.githubusercontent.com/23174198/194075152-57c68be8-7574-4af2-9356-631daeb40ef5.png)

Which is found and seen [here](https://github.com/StatCan/jupyter-apis/blob/9fcef881dd8eeda371ded319aa5c4dee00812f63/notebooks.go#L388), we are sending an empty string as a request for the volume type.

2) We might need to send something / fix something up for storageclasses(#159 ), I know @mathis-marcotte will be creating the endpoint for that but there might be another thing not too sure

Yeah as Mathis probably noted the request format changed

**Comment by mathis-marcotte** [comment]
This error is also probably related, which appears when you first open the form
![image](https://user-images.githubusercontent.com/84033116/194076940-98ec4a91-431d-4597-8272-db7bbd1280e8.png)

**Comment by Jose-Matsuda** [comment]
## How it was done previously

I'm really not sure how it does work, maybe it does some stuff [here](https://github.com/StatCan/jupyter-apis/blob/3f6d99be74258e160f1d7c0397630bfd10b5a9a8/frontend/jupyter/src/app/pages/form/form-default/volume/volume.component.html#L6) need to look more into things.

**Comment by Jose-Matsuda** [comment]
## List of Files that must change if we move to upstream's way

1) `notebooks.go`, this is where we get the error above, and in here we have definition of the `struct`s as well as the `unmarshal`s which populate the data that we retrieve from the frontend requests.

2) `config.go`, I believe this, in tandem with `spawner_ui_config.yaml` is the cause for the error mentioned by Mathis, there are again definitions of the volumes and expected request / responses.

**Comment by Jose-Matsuda** [comment]
Ok I tested in the following [gist](https://gist.github.com/Jose-Matsuda/4caa1bf34348f322a71a13825086867a) what happens if I created a struct that may or may not hold empty values, turns out its just ok (which is nice) as we might be able to just have a single struct which will hold the possible cases for each request.

**Comment by Jose-Matsuda** [comment]
Initial attempt from [this commit](https://github.com/StatCan/jupyter-apis/commit/811068a2f55ada23ead26e5b086240c7bee59408)

![image](https://user-images.githubusercontent.com/23174198/195407789-9e62371b-b72a-4f3b-aa1c-b336a34b3c7f.png)
