### ISSUE TITLE
Bug: User on dev cannot submit a notebook when only mounting a data volume

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/jupyter-apis#172]
See title, 
if user deletes the workspace volume and tries to just use a data volume (dont know why but could happen)

Greeted with 
![image](https://user-images.githubusercontent.com/23174198/196706304-5d6aa2d2-355c-4212-8565-fb909c864bcb.png)

This is probably because of me not [seeing and understanding this as a valid case to hit](https://github.com/StatCan/jupyter-apis/blob/c695a0a1b75138c3c0242db1476fc06086307661/notebooks.go#L383)

This is of lower priority i think since most people would use a workspace volume by default but who knows. Also hope its a small fix.

**Comment by chuckbelisle** [comment]
Let's see if this also happens with Blob-CSI

**Comment by mathis-marcotte** [comment]
Things that could be done to fix this are:
- Disable the Launch button when there are no workspace volumes in the form, while also letting the users know the workspace volume is mandatory(maybe a note or an icon or something?)
- Having a more user friendly error message when we specifically catch this error.

**Comment by sylus** [comment]
It isn't mandatory that you need to have a disk attach and worked before.

It is a very good use case for debugging issues.

**Comment by sylus** [comment]
Can you just get rid of the else:

https://github.com/StatCan/jupyter-apis/blob/c695a0a1b75138c3c0242db1476fc06086307661/notebooks.go#L383

**Comment by Jose-Matsuda** [comment]
> Can you just get rid of the else:
> 
> https://github.com/StatCan/jupyter-apis/blob/c695a0a1b75138c3c0242db1476fc06086307661/notebooks.go#L383

I think we could yeah.

**Comment by Jose-Matsuda** [comment]
ah nope didnt work unfortunately, need to check this
![image](https://user-images.githubusercontent.com/23174198/200640414-a6abf3c0-a3ed-442c-8462-beead6e34fd8.png)

**Comment by Jose-Matsuda** [comment]
Closed in dev by https://github.com/StatCan/aaw-kubeflow-manifests/pull/282/files
Closed in prod by https://github.com/StatCan/aaw-kubeflow-manifests/pull/283/files
