### ISSUE TITLE
Procedure to destroy old notebook volumes

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/jupyter-apis#18]
Every notebook server by default creates a volume.  Users can optionally create additional persistent volumes at notebook creation.  These are not destroyed at notebook termination.

Possible solutions:
- do we care?  If we don't mind having these persist indefinitely, close this :)
- do we have an existing way for users to cull these.  
  - If yes: add it to docs for storage
  - If no: should we?
- do we have automated garbage detection for the system to notice when users aren't culling these themselves?

**Comment by brendangadd** [comment]
As a user, I want to see all my notebook volumes and delete the ones I don't need.

Let's add UI to the Jupyter web app component of Kubeflow to enable listing and deletion of persistent volumes.
* List all of (and only) the volumes owned by the user
* Only allow deletion of volumes that are not in use – probably equivalent to having no PVC

The logic for displaying volumes and allowing deletion is probably similar to that which displays the list of existing volumes available to be attached to a new notebook server.

/cc @wg102
