### ISSUE TITLE
UI fix: Friendly add an existing volume

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#196]
This was found while testing the pipelines. It would be a UI enhancement. 

The idea would be to make it more intuitive, most likely by having a label/text and not a dropdown in the menu of type. At least in this case... It induces the user in error. 

ORIGINAL MESSAGE:
I am not sure if this is supposed to be like this, but the only option is to add a New volume. No existing.
The "Attach an existing volume" is grayed out.
![image](https://user-images.githubusercontent.com/14837042/211018298-fb8c70e1-c77b-4fe1-915d-60cf2e37a97f.png)

Addendum:
I think this is actually related to how the UI works. The type, despite being a DROPDOWN. Is just showing the default empty volume created.
![image](https://user-images.githubusercontent.com/14837042/211019114-c2cbe5f5-160b-4b34-9b13-6ffd0526c721.png)
One needs to delete the default workspace create to be able to attach the volume directly.
![image](https://user-images.githubusercontent.com/14837042/211019213-20a8c9af-38d4-48a4-88e0-ed97246bfaeb.png)

**Comment by mathis-marcotte** [comment]
New volume:
![image](https://user-images.githubusercontent.com/84033116/215101025-254c5e51-8775-4710-b5a6-d495d47556dc.png)

existing volume:
![image](https://user-images.githubusercontent.com/84033116/215101209-cb67dbb2-afd2-4a34-bb6a-9be5c9e51f30.png)
