### ISSUE TITLE
Investigate difficulty and lenght jupyter-apis common frontend to KF1.7

### ISSUE THREAD

**Issue by mathis-marcotte** [StatCan/jupyter-apis#217]
[KF1.7 EPIC](https://github.com/StatCan/aaw/issues/1632)

Step 1 is the investigation. Once that is done, appropriate size issues will be created (one to multiple, depending on result) for the size of the issues. 
For updating our common frontend folder to match [upstream](https://github.com/kubeflow/kubeflow/tree/v1.7.0/components/crud-web-apps/common/frontend) while making sure to keep any custom code we might potentially have added

We would also need to update all the common jupyter files found under [here](https://github.com/kubeflow/kubeflow/tree/v1.7.0/components/crud-web-apps/jupyter/frontend). This would be excluding everything found under `/cypress`, `/i18n` and `/src/app/pages` as those will be handled in other issues.

**Comment by wg102** [comment]
There are a few new things in the common folders:
- Linting : eslintrc.js file + a script for the check-spelling errors
On top of quite a new front-end folders.
- content-list-item
- editor
- help-popover
- logs-viewer
- status-icon
- urls
- variations-group-table


This confirms the ticket might be a 5 for the difficulty
