### ISSUE TITLE
Update jupyter-apis i18n to KF1.7

### ISSUE THREAD

**Issue by mathis-marcotte** [StatCan/jupyter-apis#221]
Once all the code is updated for the frontend, we should make sure to run `npm run i18n:extract` to update the messages files for our translations, and also add any missing translation.

Since updating xliff files can be annoying, maybe we can look into a tool like [xliffmerge](https://www.npmjs.com/package/ngx-i18nsupport) to help us out.

List of files 
# I18n
jupyter/frontend/i18n/fr
- [x] OWNERS
- [x] messages.fr.xlf

jupyter/frontend/i18n/
- [x] messages.xlf

jupyter/frontend/src/app/pages/form/form-new/form-cpu-ram
- [x] form-cpu-ram.component.html

jupyter/frontend/src/app/pages/form/form-new/form-data-volumes
- [x] form-data-volumes.component.html

jupyter/frontend/src/app/pages/form/form-new/form-image
- [x] form-image.component.html
There is also new text we will need to figure out for this one for the description of the SAS image

**Comment by wg102** [comment]
# Notes from other tickets: 

projects/kubeflow/src/lib/confirm-dialog:
- types.ts : Will need to translate?
-
projects/kubeflow/src/lib/content-list-item:
- Entirely new thing. Will need to be translated

projects/kubeflow/src/lib/editor: New folder
- Will need translation?

projects/kubeflow/src/lib/editor/interfaces: New folder
- Will need translation?

projects/kubeflow/src/lib/form/rok-url-input:
- New content but this is all untranslated. We don't use rok.


section.component.html : Customization conflict.
- New help section
projects/kubeflow/src/lib/form/section-image:
- Will need to investigate when in that section and make the necessary adjustments.

projects/kubeflow/src/lib/help-popover: New

- New

projects/kubeflow/src/lib/loading-spinner: 
- new css class may needed translation

projects/kubeflow/src/lib/logs-viewer: New



namespace-select.component.html 
- Will need to confirm new option
namespace-select.component.ts 
- New input + lots of code changes

projects/kubeflow/src/lib/resource-table/action:
The following might be translation troubles:
- action.component.html went from matTooltip="{{ tooltipReady }}" to matTooltip="{{ action.tooltip }}"
- action.component.html went from matTooltip="{{ tooltipInit }}" to matTooltip="{{ action.tooltip }}"

projects/kubeflow/src/lib/resource-table/component-value:
- component-value.component.ts New output

projects/kubeflow/src/lib/resource-table/types:
- index.ts new link to link-value
- property-value.ts Make links actual links 
- table.ts New code handles links
These will need to be thoroughly checked for translation, especially the new link feature

projects/kubeflow/src/lib/resource-table/table: 
- MANY CHANGES All these might be trouble when trying to run the code and for translation

table.component.html 
- MANY new translations. Like MANY
- utils.ts New file

namespace.service.ts It's like if there was only half a refactor on the file
projects/kubeflow/src/lib/services:


projects/kubeflow/src/lib/status-icon: New
- Will need translation

projects/kubeflow/src/lib/title-actions-toolbar:
- title-actions-toolbar.component.html New code with tooltip might need translation

- title-actions-toolbar.module.ts New mattooltip module
- projects/kubeflow/src/lib/urls: New
Will need translation

projects/kubeflow/src/lib/variables-groups-table: 
- New will need translation

**Comment by mathis-marcotte** [comment]
### Will need translations

frontend/jupyter/src/app/pages/index/index-default
- /index-default.component.ts

**Comment by wg102** [comment]
Will need to translate 
Protected B page
Custom image page

**Comment by mathis-marcotte** [comment]
Looked into the xliffmerge type of tools but they weren't really working, or working well enough, when i looked into them. Either our angular version was blocking them from being installed or some other issues like the outputs weren't really any better than what we have. 
So I'll just update the translation files like we've done in the past.

**Comment by mathis-marcotte** [comment]
Looks like some text was added under frontend/common/kubeflow/kubeflow-common-lib. We have never had text to have to update coming from that part of the repo, and since it is split from frontend/jupyter where our i18n is setup, it is not being currently translated.
So I'll have to look into how we can make that kubeflow lib translatable.

**Comment by mathis-marcotte** [comment]
Since the text was all mostly in the common table component, decided to just make it so that that text is an input of that component. So that means we can set the text in our frontend/jupyter side of the app and translate it there, and then send the translated text to the kubeflow-common-lib side of the app.

**Comment by mathis-marcotte** [comment]
Some follow ups:

- https://github.com/StatCan/jupyter-apis/issues/271
- https://github.com/StatCan/jupyter-apis/issues/272
