### ISSUE TITLE
Display cost estimates for namespace

### ISSUE THREAD

**Issue by brendangadd** [StatCan/jupyter-apis#25]
As a user, I want to see an estimated daily cost of the resources I'm using. I want to see this broken down by type of resource (e.g. compute, storage, specialized hardware like GPUs).

* The _Notebook Servers_ view is a decent place to show this information.
* It's okay if the reported costs include all resources of the selected namespace. It doesn't have to be limited to just the resources displayed in the current view (e.g. `notebook` resource type).

**Comment by saffaalvi** [comment]
@sylus 
<img width="968" alt="Screen Shot 2020-10-13 at 4 24 04 PM" src="https://user-images.githubusercontent.com/57377830/95912212-842d6d80-0d70-11eb-8a50-5a11a1695634.png">

**Comment by sylus** [comment]
Wow @saffaalvi that is so incredibly cool, great job!

**Comment by saffaalvi** [comment]
@sylus Thank you!
