### ISSUE TITLE
Add visual loading indicator for when data takes longer to load

### ISSUE THREAD

**Issue by mathis-marcotte** [StatCan/jupyter-apis#257]
Sometimes it feels like it takes a little bit of time to load the data in the tables, so it appears for a little bit of time as if there is nothing in the namespace. 
Might be a good idea to either optimize the data fetches and/or add a visual indicator for the initial loading of the data.

**Comment by wg102** [comment]
This is for the two visible tables on jupyter-api. The notebooks and volumes. Might no longer  be an issue, but it also might.

**Comment by wg102** [comment]
Current plan is to add a boolean value that gets set to true the very first time data is received, and by default it will show a loader until it does.
This way, it covers the 'how long until we show a message' question.

**Comment by wg102** [comment]
![image](https://github.com/StatCan/jupyter-apis/assets/14837042/960f9865-5584-4d7a-82de-fb3d55166049)
