### ISSUE TITLE
Notebook Creation: leading/trailing spaces in custom image name

### ISSUE THREAD

**Issue by Souheil-Yazji** [StatCan/jupyter-apis#288]
/kind bug
Add frontend validation in the notebook creation page to prevent the following error: 
![image](https://github.com/StatCan/kubeflow/assets/35379392/425c2aef-4a0d-4df2-adbb-eab364353bc3)

Can be committed to upstream.

**Comment by mathis-marcotte** [comment]
fix from upstream : https://github.com/kubeflow/kubeflow/pull/7026
