### ISSUE TITLE
refactoring the use of global variables

### ISSUE THREAD

**Issue by saffaalvi** [StatCan/jupyter-apis#31]
Some handlers are using global variables defined in `main.go`. These need to be added to the `server struct` instead of referencing them globally. 

Some steps to change `server struct` in `main.go`:
- ~Already has `Config`; refactor all references, types, and functions for existing `Config` to `ClientConfig`~
- ~Add a new struct, `ServerConfig` that has fields for all the configuration the handlers need access to~
- Now you can pass any params required to `server` and they will be accessible in the handlers

**Comment by brendangadd** [comment]
Strike-through in description is mine. The refactoring was my original direction, but @saffaalvi implemented the `kubecostUrl` as a field directly on the `server` struct and it reads/works well.

So remaining globals can be added directly to the struct in a similar manner and we'll save ourselves some refactoring until it's more warranted.
