### ISSUE TITLE
Enforce that new GPU notebook servers requests book the entire machine

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/jupyter-apis#37]
GPU nodes are used solely for workflows which need GPUs due to ~10x costs per node (GPU node = $3-4/hr, regular node ~0.46/hr @ 1-year reserved rate, 0.768/hr if not reserved).  Costing passed to users is prorated by how much of a machine a user requests (request half a machine's CPU/RAM, pay for half the machine's costs).  

Any user that requests a GPU will result in a new full GPU node spun up.  Regardless of how much of the node the user occupies, the platform is charged for a full node.  But if the user reserves only a part of that node (say 20% of RAM and 20% of CPU, plus the GPU) they don't get billed for the rest of the idle CPU/RAM they've caused.

Suggested solution: require that a GPU notebook server be booked as a full machine, therefore passing the full cost to the user.  In our case, that means requiring that any GPU request be for 5CPU/96GB RAM.

**Comment by ca-scribner** [comment]
This could be completed alongside #36

**Comment by ca-scribner** [comment]
(before anyone actually does this, we need agreement on if we should do it.  I think we should, but that wasn't a concensus)

**Comment by Nancy-Badran** [comment]
ok, good to know

**Comment by blairdrummond** [comment]
@ca-scribner I think this makes sense. Also, confirming what @chritter thought, the input from the notebook-server form fills the `require` and `limit` fields

```
Containers:                    
  tf-test:                               
    Image:      k8scc01covidacr.azurecr.io/blairs-vscode-tf
    Port:       8888/TCP                                                                                                                                                                       
    Host Port:  0/TCP             
    Limits:      
      cpu:             1                                                                                                                                                                       
      memory:          2Gi       
      nvidia.com/gpu:  1
    Requests:       
      cpu:             1                                                                       
      memory:          2Gi
      nvidia.com/gpu:  1
    Environment:          
      NB_PREFIX:  /notebook/blair-drummond/tf-test
```

So jobs would get evicted (unnecessarily) if they use more than 2gb of RAM on those GPU nodes.

So setting the fields to high/max values also will ensure that no jobs get evicted unnecessarily.
