### ISSUE TITLE
Validate notebook server PVCs on server creation

### ISSUE THREAD

**Issue by ca-scribner** [StatCan/jupyter-apis#50]
Current state: 

Users can try to create notebook servers that request mounting a read-write-once (single user) data volume that is already in use.  This results in a notebook server that will never fully start

Proposal:

Validate the user's request for volumes on the new notebook server prior to submission, alerting them to this error.  The page already shows PVC status, so this information should be accessible somehow.  This way users don't get stuck with machines that never start, which is both frustrating and causes them to ask us for help.

**Comment by wg102** [comment]
The first commit to the draft PR adds the error message in the model. But it does not automatically show in a specific case: when the element has yet to be touched. Currently working on this, the solution should be something specific to material angular.
