### ISSUE TITLE
Add validation to new notebooks server view

### ISSUE THREAD

**Issue by brendangadd** [StatCan/jupyter-apis#7]
### Name
* Contain at most 63 characters
* Contain only lowercase alphanumeric characters or '-'
* Start with an alphanumeric character
* End with an alphanumeric character

### CPU/RAM
* Must be possible to schedule this configuration
* This depends on analysis from Cloud Native team, so may need to fall into separate issue
* _Challenging: valid input differs across node pools_

### Workspace Volumes
* Switch to a menu* with options that align to Azure disk sizes – we pay for the whole thing anyway
* Limit the size of these volumes; data volumes should be used for large volumes
* _* Above constraint could actually result in a static workspace volume size, depending on minimum disk size_

### Data Volumes
* Switch to a menu with options that align to Azure disk sizes – we pay for the whole thing anyway

### GPU
* Would be cool if selecting a number of GPUs automatically set CPU/RAM to an appropriate ratio – for current node pools, that would mean consuming the node when GPU is 1

**Comment by blairdrummond** [comment]
@brendangadd for the GPUs, my understanding is that it *doesn't matter* what you select so long as you don't go over the resource limits. I think it's one-node per user and only other processes that can be on there are the daemon-sets. So if it simplifies things, we might be able to just auto-fill and prevent user modification on GPU images.

@zachomedia can correct me!

**Comment by brendangadd** [comment]
The data volumes are [Azure Managed Disks][disks] (`StandardSSD_LRS`) – see this link for available sizes. Volume sizes should align to the disk sizes so we aren't paying for storage that can't be accessed by the user.

* **Workspace volume:** dropdown with options in range E1 to E4, defaulting to E1
* **Data volume:** dropdown with options in range E1 to E20, defaulting to E3

Don't support entry of custom values at this time. If we find above configuration is too constrained, then we can deal with it in a separate issue – and consider expanding the dropdown in favour of allowing custom input.

/cc @saffaalvi 

[disks]: https://azure.microsoft.com/en-us/pricing/details/managed-disks/

**Comment by ca-scribner** [comment]
For drive size, did we ever check to make sure we're actually getting the outcome we want (that users get exactly the size drive they asked, not a bigger drive that has dead space)?  I think I'm worried about nothing, but wondering if there's some rounding or something that happens in the request.
