### ISSUE TITLE
JWA customization: Volume Custom Validation

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#72]
Work to get JWA with 1.3 kubeflow.

  - [Merge pull request #51 from StatCan/50-add-validation-mounted-pvc](https://github.com/StatCan/jupyter-apis/commit/8641aabbd270e1c2d096a7c7e54f62050ae51048)
    - [feat: Add validation for mounted pvc](https://github.com/StatCan/jupyter-apis/pull/51/commits/f2614b68f6858c904b8b2f2292228e97efbb9b29)
    - [fix: show error when element is untouched](https://github.com/StatCan/jupyter-apis/pull/51/commits/22805a3f9dd5d39f3c99985d0bc68b9425f0fd53)

**Comment by Jose-Matsuda** [comment]
Reopening since I don't think this was covered by the mega pr
