### ISSUE TITLE
JWA customization: Kubecost

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#75]
Work to get JWA with 1.3 kubeflow.

  - [Merge pull request #27 from StatCan/kubecost-estimates](https://github.com/StatCan/jupyter-apis/commit/49dea695f64485252348b72608af0b7886d05cb6)
    - [feat: add cost estimate table](https://github.com/StatCan/jupyter-apis/pull/27/commits/b08cb8844caa2e57fba5ff29ff476a7177859c61)
    - [fix: connect to Kubecost API + cleanup and refactor components](https://github.com/StatCan/jupyter-apis/pull/27/commits/2284c4d49fd7c7dc13922ec07fd669b5bf1b2e8e)
  - [Merge pull request #34 from StatCan/fix-kubecost-error](https://github.com/StatCan/jupyter-apis/commit/d412a39fca66e4ae70c78742555c01f0e01ea11f)
    - [fix: add check for kubecost error response + translation](https://github.com/StatCan/jupyter-apis/pull/34/commits/460f113d6447e3541a8b9383c9b613386314b46f) 
  - [Merge pull request #40 from StatCan/fix-kubecost-message](https://github.com/StatCan/jupyter-apis/commit/0fba437b5f3965c141407dd5bd51ac2289570faa)
    - [fix: kubecost table message](https://github.com/StatCan/jupyter-apis/pull/40/commits/aeddf810fb0a20916ad4c2f990ad1a85ff0a54ee)

**Comment by rohank07** [comment]
`{"success":false,"status":500,"log":"subjectaccessreviews.authorization.k8s.io is forbidden: User \"saffa.alvi@cloud.statcan.ca\" cannot create resource \"subjectaccessreviews\" in API group \"authorization.k8s.io\" at the cluster scope","user":"user"}` Dev cluster RBAC will need to be modified for kubecost. 
cc @sylus

**Comment by wg102** [comment]
Closed by https://github.com/StatCan/jupyter-apis/pull/92
