### ISSUE TITLE
JWA Customization: Notebook Server Validation

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/jupyter-apis#76]
First task in https://github.com/StatCan/jupyter-apis/issues/68

Look through

[Merge pull request #19 from StatCan/notebook-server-validation](https://github.com/StatCan/jupyter-apis/commit/22bdc135476e5eaa17318bf635d79aa5890ad888) which includes the following

- [fix: notebook server validation](https://github.com/StatCan/jupyter-apis/pull/19/commits/1e666335ee1f08251652335eacb5e721d4fd0870) -> the form-name.component.html seems to have changed from what we had, to whats in 1.3 significantly.
- [fix: Fix cross-validation issues, error messages](https://github.com/StatCan/jupyter-apis/pull/19/commits/32eb310e955fd2e02ea8cec18edfd56ceea11827)
- [fix: Gi for RAM not optional](https://github.com/StatCan/jupyter-apis/pull/19/commits/9cbb66cb47c31ff516c8ea89f11551022b2aa4bb)

This is done by me comparing 1.1 to current (1.3)

**Comment by Jose-Matsuda** [comment]
So looking through these files in order from top to bottom
https://github.com/StatCan/jupyter-apis/commit/22bdc135476e5eaa17318bf635d79aa5890ad888

`frontend/.prettierrc` seems to be fine

`frontend/src/app/resource-form/form-data-volumes/form-data-volumes.component.html` I have added

**Comment by Jose-Matsuda** [comment]
Validation confirmed working without any modifications necessary (built off of main)for:
Name
![image](https://user-images.githubusercontent.com/23174198/155008423-aaaa2b68-4a86-407e-beab-6979a8c0008d.png)
(tried the other no no's)
and Volumes
![image](https://user-images.githubusercontent.com/23174198/155008481-7f869452-c29f-4263-b65b-d9900deff1b2.png)

**Comment by Jose-Matsuda** [comment]
# THINGS REGARDING UPSTREAMING
Under this are any special notes that we should _note_ when talking about upstreaming specific to this task
1) The `Workspace Volume` customization where instead of letting users select their own size we give them a set of sizes to choose from. This is for the `volume.component.html`
![image](https://user-images.githubusercontent.com/23174198/155012646-fcbc1d02-e3f9-4c11-90b1-609e13056e99.png)
![image](https://user-images.githubusercontent.com/23174198/155012702-699aef4a-29cd-46ba-9967-24ddf5045621.png)
and it seems to use the same as the cpu/ram selector. on the direct right under 'Size' is what is uncommented in the code above. The red arrow points to what is in comment

**Comment by wg102** [comment]
Closed by https://github.com/StatCan/jupyter-apis/pull/92
