### ISSUE TITLE
Explore connecting to local instance of Kubeflow

### ISSUE THREAD

**Issue by brendangadd** [StatCan/jupyter-apis#8]
Find a way to connect this component to a local instance of Kubeflow so local development can be done with less risk and permission issues.

The API server falls back to using the current `kubectl` context (i.e. `kubectl config current-context`) for connecting to a master node, and it just issues standard Kubernetes API requests from there. So this task essentially amounts to:

* Setting up a local Kubeflow cluster
* Configuring a `kubectl` context for that cluster
* Overcoming any divergence between local and production clusters (e.g. lack of Istio)

For local cluster installation, I recommend beginning with the MiniKF option described in the [Kubeflow docs][].

[kubeflow docs]: https://www.kubeflow.org/docs/started/workstation/

**Comment by blairdrummond** [comment]
I think that microk8s on ubuntu also comes with kubeflow out-of-the-box

**Comment by zachomedia** [comment]
https://kind.sigs.k8s.io is also an option for running a cluster locally
