### ISSUE TITLE
JWA Customization: Cpu/Gpu

### ISSUE THREAD

**Issue by rohank07** [StatCan/jupyter-apis#80]
[Merge pull request #12 from StatCan/fix-kubeflow-collision-information](https://github.com/StatCan/jupyter-apis/commit/5caa0a449bf31913e88f241c343cb5578810ba87)

- [fix: kubeflow collision](https://github.com/StatCan/jupyter-apis/commit/f068e8d34f8ad4f0768a0baa078cb838d0711130)

[Merge pull request #38 from StatCan/fix-max-limits](https://github.com/StatCan/jupyter-apis/commit/344d4fcae658d5136bbc772896025d589ad43873)

- [fix: update ram limits](https://github.com/StatCan/jupyter-apis/pull/38/commits/f8c29eecb38e96b24933fa7932497218cb47ef60)

[Merge pull request #45 from StatCan/fix-gpu-specs](https://github.com/StatCan/jupyter-apis/commit/0e116fd92e406d308f5474947bb8e9547127e11c)

- [fix: set max cpu/ram values for 1 gpu + translation](https://github.com/StatCan/jupyter-apis/commit/6c5fa37258d6b3df7bafba5538655f64f5f3c5e9)

[Merge pull request #57 from StatCan/lower-gpu-cpu-request](https://github.com/StatCan/jupyter-apis/commit/0b55d4da2ac2b43dbcbc0331a4d404366af6d788)

- [fix: lower gpu node cpu-request to allow scheduling](https://github.com/StatCan/jupyter-apis/pull/57/commits/33372de4d74ec36b8e92c3b9edfa80ef4ab809ef)

**Comment by Jose-Matsuda** [comment]
Closed by https://github.com/StatCan/jupyter-apis/pull/92
