### ISSUE TITLE
JWA Customization: Errors

### ISSUE THREAD

**Issue by rohank07** [StatCan/jupyter-apis#81]
[Merge pull request #9 from StatCan/fix-angular-component](https://github.com/StatCan/jupyter-apis/commit/f0b855dec4d375a0c06d521d404e4a6da4b8d30a)

- [fix: angular mat-form-fiel error](https://github.com/StatCan/jupyter-apis/pull/9/commits/20ff2f912e7afc661116a5e4618fdd2bea016ad1)

[Merge pull request #23 from StatCan/fix-dependabot-alerts](https://github.com/StatCan/jupyter-apis/commit/1a50addb5e0703409dd5954d6aaeb68e35458b2c)

- [fix: resolve dependabot alerts](https://github.com/StatCan/jupyter-apis/pull/23/commits/faf54151b9873bb42c8c7be8f5211e95c5bbb5e1)

- [fix: browser console ExpressionChanged error](https://github.com/StatCan/jupyter-apis/pull/23/commits/d2a95378554f5523f626f947d0da37909f8f2548)

**Comment by wg102** [comment]
Closed by https://github.com/StatCan/jupyter-apis/pull/92
