### ISSUE TITLE
JWA: i18n and relative paths for fetching translation files 

### ISSUE THREAD

**Issue by wg102** [StatCan/jupyter-apis#93]
The i18n isn't functioning properly.

This is apparently a known issue if you take a look at the discussion here:

- https://github.com/kubeflow/kubeflow/pull/6034

The following needs to be fixed:

- [ ] i18n loading
- [ ] kubecost text

![image](https://user-images.githubusercontent.com/14837042/156640649-9b0211e7-f112-41c9-acc8-7ffcf00c9eb8.png)
![image](https://user-images.githubusercontent.com/14837042/156640754-712c044e-d9b8-4513-a0e2-01a752d32948.png)
![image](https://user-images.githubusercontent.com/14837042/156640841-b455bd15-7020-4e14-b4a9-6468d2808162.png)
![image](https://user-images.githubusercontent.com/14837042/156640901-63e91fba-3954-4ddd-ad28-a89c661635ff.png)
![image](https://user-images.githubusercontent.com/14837042/156641091-fe7a7cfd-e3de-4287-a09f-56985e223fb7.png)

**Comment by wg102** [comment]
The i18n was fixed byt this PR: https://github.com/StatCan/jupyter-apis/pull/97

**Comment by sylus** [comment]
The full i18n was resolved by correcting the assets path as well as a few updates to the main controller.

This was put in as a single merge commit so can easily see the fully context of changes.

https://github.com/StatCan/jupyter-apis/commit/813f13a1d8590d0e11364dd17322ae1caaaae1f6
